version: '3.8'

services:
  booking-app:
    image: ghcr.io/zateckar/booking:latest
    ports:
      - "8000:8000"
    volumes:
      - booking_data:/app/data
      - booking_logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/login"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - booking-network

volumes:
  booking_data:
    driver: local
  booking_logs:
    driver: local

networks:
  booking-network:
    driver: bridge
