services:
  booking-app:
    image: ghcr.io/zateckar/booking:latest
    ports:
      - "8000:8000"
    volumes:
      # User data directories
      - booking_data:/app/data
      - booking_logs:/app/logs
      # User uploads and customizations
      - booking_uploads:/app/static/uploads
      - booking_parking_images:/app/static/images/parking_lots
    environment:
      # Initial Admin User (for first-time setup)
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL:-admin@example.com}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD:-change-this-secure-password}
      - SESSION_SECRET_KEY=your-secure-key
      - USE_HTTPS=true
      - BASE_URL=https://example.com
      - ENVIRONMENT=production
      - DATABASE_URL=sqlite:///data/booking.db
    restart: unless-stopped
    networks:
      - booking-network

volumes:
  booking_database:
  booking_data:
  booking_logs:
  booking_uploads:
  booking_parking_images:

networks:
  booking-network:
