services:
  booking-app:
    image: ghcr.io/zateckar/booking:latest
    ports:
      - "8000:8000"
    volumes:
      - booking_data:/app/data
      - booking_logs:/app/logs
    restart: unless-stopped
    networks:
      - booking-network

volumes:
  booking_data:
    driver: local
  booking_logs:
    driver: local

networks:
  booking-network:
