services:
  booking-app:
    image: ghcr.io/zateckar/booking:latest
    ports:
      - "8000:8000"
    volumes:
      - booking_data:/app/data
      - booking_logs:/app/logs
    environment:
      # Initial Admin User (for first-time setup)
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL:-admin@example.com}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD:-change-this-secure-password}
    restart: unless-stopped
    networks:
      - booking-network

volumes:
  booking_data:
    driver: local
  booking_logs:
    driver: local

networks:
  booking-network:
