services:
  booking-app:
    image: ghcr.io/zateckar/booking:latest
    ports:
      - "8000:8000"
    volumes:
      - booking_data:/app/data
      - booking_logs:/app/logs
    # Run as current user to resolve volume permission issues
    # Default to 1000:1000, but can be overridden with DOCKER_USER environment variable
    user: "${DOCKER_USER:-1000:1000}"
    environment:
      # Initial Admin User (for first-time setup)
      - INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL:-admin@example.com}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD:-change-this-secure-password}
      - ENVIRONMENT=production
    restart: unless-stopped
    networks:
      - booking-network

volumes:
  booking_data:
    driver: local
  booking_logs:
    driver: local

networks:
  booking-network:
